import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { ThemeProvider } from "@/components/ThemeProvider";

import { Header } from "@/components/Header";

const inter = Inter({ subsets: ["latin"] });

import { TanstackProvider } from "@/components/TanstackProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={cn(inter.className, "dark:bg-black")}>
        <TanstackProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
            <div className={cn("max-w-[1200px] mx-auto p-6 pb-10", "lg:py-14")}>
              <Header />
              {children}
            </div>
          </ThemeProvider>
        </TanstackProvider>
      </body>
    </html>
  );
}
